[package]
name = "selendra"
version = "0.1.0"
authors = ["Selendra <info@selendra.org>"]
edition = "2021"
default-run = "selendra"

[[bin]]
name = "selendra"
path = "src/main.rs"

[dependencies]
futures = "0.3.21"
parity-util-mem = { version = "0.11", default-features = false, features = ["jemalloc-global"] }
selendra-cli = { path = "cli" }

[features]
default = []

runtime-benchmarks = [
	"selendra-cli/runtime-benchmarks",
]
